vich_uploader:
    db_driver: orm

    mappings:
        collections:
            uri_prefix: /images/collections
            upload_destination: '%kernel.project_dir%/public/images/collections'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
